<?php
/**
  @file
  @brief The Hockey Boss Stat module creates the
    Stat content types used by the Hockey Boss
    site.
*/

/// Implements hook_permission ().
function hockey_boss_stat_permission () {
  return array (
    'hockey_boss_stat_edit_all_pps' => array (
      'title'       => t ('Edit All Player Performance Stats'),
      'description' => t ('Enables users to edit all player performance stats.')
    ),
    'hockey_boss_stat_edit_own_pps' => array (
      'title'       => t ('Edit Own Player Performance Stats'),
      'description' => t ('Enables a user to edit their own player performance stats.')
    ),
    'hockey_boss_stat_edit_team_pps' => array (
      'title'       => t ('Edit Team Player Performance Stats'),
      'description' => t ('Enables a user to edit the player performance stats of team members.')
    ),
    'hockey_boss_stat_edit_all_pfs' => array (
      'title'       => t ('Edit All Player Fitness Stats'),
      'description' => t ('Enables users to edit all player fitness stats.')
    ),
    'hockey_boss_stat_edit_own_pfs' => array (
      'title'       => t ('Edit Own Player Fitness Stats'),
      'description' => t ('Enables a user to edit their own player fitness stats.')
    ),
    'hockey_boss_stat_edit_team_pfs' => array (
      'title'       => t ('Edit Team Player Fitness Stats'),
      'description' => t ('Enables a user to edit the player fitness stats of team members.')
  ));
}
