<?php
/**
  @file
*/

/// Implements hook_view_api ().
function soccer_boss_views_api () {
  return array ('api' => 3.0);
}

/**
  @brief Implements hook_block_info_alter ().
  @details
    Enables the core blocks and moves them to their
    designated regions.
  @see soccer_boss_block_settings ().
  @see soccer_boss_set_block_visibilities ().
*/
function soccer_boss_block_info_alter (&$blocks, $theme, $code_blocks) {
  module_load_include ('inc', 'soccer_boss');

  foreach (soccer_boss_block_settings () as $delta => $settings) {
    $module = $settings ['module'];

    if (empty ($blocks [$module][$delta]['pages'])) {
      $blocks [$module][$delta]['status']     = 1;
      $blocks [$module][$delta]['region']     = $settings ['region'];
      $blocks [$module][$delta]['visibility'] = 1;
      $blocks [$module][$delta]['pages']      = 'node/*';
    }
  }
}

/// Implements hook_menu ().
function soccer_boss_menu () {
  return array (
    // I. Defines the Coach menu tabs.
    'node/%node/team' => array (
      'title'            => t ('Team'),
      'description'      => t ('Redirects the user to the team associated with the given coach\'s node id.'),
      'access callback'  => '_soccer_boss_check_type',
      'access arguments' => array (1, 'soccer_boss_coach'),
      'page callback'    => 'soccer_boss_coach_team_page',
      'page arguments'   => array (1),
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'soccer_boss.page.inc',
      'weight'           => 1
    ),
    // II. Defines the Player menu tabs.
    'node/%node/stats' => array (
      'title'            => t ('Stats'),
      'description'      => t ('Redirects the user to the stats page.'),
      'access callback'  => '_soccer_boss_check_type',
      'access arguments' => array (1, 'soccer_boss_player'),
      'page callback'    => 'soccer_boss_player_stats_page',
      'page arguments'   => array (1),
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'soccer_boss.page.inc',
      'weight'           => 1
    ),
    'node/%node/team' => array (
      'title'            => t ('Team'),
      'description'      => t ('Redirects the user to the player\'s team page.'),
      'access callback'  => '_soccer_boss_check_type',
      'access arguments' => array (1, 'soccer_boss_player'),
      'page callback'    => 'soccer_boss_player_team_page',
      'page arguments'   => array (1),
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'soccer_boss.page.inc',
      'weight'           => 1
    ),
    // III. Defines the Team menu tabs.
    'node/%node/coach' => array (
      'title'            => t ('Coach'),
      'description'      => t ('Displays information about the team\'s coach.'),
      'access callback'  => '_soccer_boss_check_type',
      'access arguments' => array (1, 'soccer_boss_team'),
      'page callback'    => 'soccer_boss_team_coach_page',
      'page arguments'   => array (1),
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'soccer_boss.page.inc',
      'weight'           => 1
    ),
    'node/%node/roster' => array (
      'title'            => t ('Roster'),
      'description'      => t ('Lists the team\'s players.'),
      'access callback'  => '_soccer_boss_check_type',
      'access arguments' => array (1, 'soccer_boss_team'),
      'page callback'    => 'soccer_boss_team_roster_page',
      'page arguments'   => array (1),
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'soccer_boss.page.inc',
      'weight'           => 2
    ),
    'node/%node/games' => array (
      'title'            => t ('Matches'),
      'description'      => t ('Lists the team\'s past and upcoming matches.'),
      'access callback'  => '_soccer_boss_check_type',
      'access arguments' => array (1, 'soccer_boss_team'),
      'page callback'    => 'soccer_boss_team_games_page',
      'page arguments'   => array (1),
      'type'             => MENU_LOCAL_TASK,
      'file'             => 'soccer_boss.page.inc',
      'weight'           => 3
    )
  );
}

/**
  @brief Defines a menu access callback that
    returns true iff the given node has the given
    type.
  @param $node (object) the referenced node.
  @param $type (string) the required node type.
  @return (boolean).
*/
function _soccer_boss_check_type ($node, $type) {
  watchdog (
    'soccer_boss',
    '[_soccer_boss_check_type] node type: @node_type type: @type',
    array (
      '@node_type' => $node->type,
      '@type'      => $type
  ));

  return $node->type == $type;
}
