<?php
/**
  @file
  @brief This module defines an API for creating
    stat nodes. Stat nodes are nodes that are used
    to represent statistics and share a set of core
    fields.
*/

/**
  @brief Implements hook_node_type_delete ().
  @details
    Deletes the stat type associated with the node
    type that is being deleted.
*/
function stat_node_type_delete ($info) {
  module_load_include ('inc', 'stat');
  $stat_types = array_merge (
    stat_type_get_by_node_type ($info->type),
    stat_type_get_by_subject_node_type ($info->type)
  );
  stat_type_delete_multiple ($stat_types);
}

/**
  @brief Implements hook_node_delete ().
  @details Deletes those stats that reference a
    node that is being deleted.
*/
function stat_node_delete ($node) {
  module_load_include ('inc', 'stat');
  foreach (stat_type_get_all () as $stat_type) {
    foreach (stat_node_get_by_subject ($stat_type ['node_type'], $node->nid) as $stat_node) {
      node_delete ($stat_node);
    }
  }
}
