<?php
/**
  @file
  @brief Defines the chart blocks and AJAX callback functions.
  @see http://code.google.com/p/drupal-chart-api/wiki/Examples
*/

/// Implements hook_block_info ().
function soccer_boss_chart_block_info () {
  return array (
    'soccer_boss_chart_pfs' => array (
      'info' => t ('Charts a player\'s fitness stats over time.')
  ));
}

/// Implements hook_block_view ().
function soccer_boss_chart_block_view ($delta = '') {
  module_load_include ('inc', 'soccer_boss');
  module_load_include ('inc', 'soccer_boss_chart');

  $node = menu_get_object ();
  switch ($delta) {
    case 'soccer_boss_chart_pfs':
      if ($node && $node->type == soccer_boss_PLAYER_TYPE) {
        $_SESSION ['soccer_boss']['chart_data'] = _soccer_boss_chart_pfs ($node);
        return array (
          'subject' => t ('Player Fitness Stats'),
          'content' => drupal_get_form ('soccer_boss_chart_form')
        );
      }
      break;
  }
}

/// The AJAX callback for the Next button in the Chart form.
function _soccer_boss_chart_next () {
  array_push ($_SESSION ['soccer_boss']['chart_data'],
              array_shift ($_SESSION ['soccer_boss']['chart_data']));

  return drupal_get_form ('soccer_boss_chart_form');
}

/// The AJAX callback for the Previous button in the Chart form.
function _soccer_boss_chart_prev () {
  array_unshift ($_SESSION ['soccer_boss']['chart_data'],
                 array_pop ($_SESSION ['soccer_boss']['chart_data']));

  return drupal_get_form ('soccer_boss_chart_form');
}

/**
  @brief Returns a form that allows users to cycle through charts.
  @return (array) the form array.
  @note The charts are defined by the
    $_SESSION ['soccer_boss']['chart_data'] session variable.
*/
function soccer_boss_chart_form ($form, $form_state) {
  module_load_include ('inc', 'soccer_boss_chart');

  if (!isset ($_SESSION ['soccer_boss']['chart_data']) || empty ($_SESSION ['soccer_boss']['chart_data'])) {
    return array ();
  }

  $data = $_SESSION ['soccer_boss']['chart_data'];

  $chart = soccer_boss_chart ($data [0]);

  return array (
    'pager' => array (
      '#type' => 'fieldset',
      '#prefix' => '<div id="soccer_boss_fitness_chart">' . theme ('chart', array ('chart' => $chart)),
      '#suffix' => '</div>',

      'next_button' => array (
        '#type'  => 'button',
        '#value' => t ('Next'),
        '#ajax'  => array (
          'callback' => '_soccer_boss_chart_next',
          'wrapper'  => 'soccer_boss_fitness_chart'
      )),
      'prev_button' => array (
        '#type'  => 'button',
        '#value' => t ('Prev'),
        '#ajax'  => array (
          'callback' => '_soccer_boss_chart_prev',
          'wrapper'  => 'soccer_boss_fitness_chart'
      ))
    )
  );
}
